import test from "node:test";
import assert from "node:assert/strict";
import {
  PRESCRIPTION_COMPUTER_GENERATED_DISCLAIMER,
  buildPrescriptionPrintHtml,
  formatPrescriptionPlainText,
} from "./prescription-format.js";

const DRAFT = {
  medications: [
    {
      name: "Azithral",
      dosage: "500mg",
      frequency: "1-0-0",
      duration: "3 days",
      instructions: "after food",
    },
  ],
  advice: ["Rest"],
  investigations: [],
  followUpDays: 5,
};

const PATIENT = { name: "Ravi", age: 32, gender: "Male" };

test("formatPrescriptionPlainText includes registration number when license_number is set", () => {
  const text = formatPrescriptionPlainText({
    draft: DRAFT,
    patient: PATIENT,
    doctor: {
      full_name: "Priya Sharma",
      clinic_name: "Care Clinic",
      license_number: "MCI-123456",
    },
  });

  assert.match(text, /Care Clinic/);
  assert.match(text, /Dr\. Priya Sharma/);
  assert.match(text, /Reg\. No\. MCI-123456/);
  assert.equal(
    (text.match(/Reg\. No\. MCI-123456/g) ?? []).length,
    2,
    "registration should appear in header and footer",
  );
});

test("formatPrescriptionPlainText omits registration line when license_number is missing or blank", () => {
  for (const doctor of [
    { full_name: "Priya Sharma", clinic_name: "Care Clinic" },
    { full_name: "Priya Sharma", clinic_name: "Care Clinic", license_number: null },
    { full_name: "Priya Sharma", clinic_name: "Care Clinic", license_number: "   " },
  ]) {
    const text = formatPrescriptionPlainText({
      draft: DRAFT,
      patient: PATIENT,
      doctor,
    });
    assert.doesNotMatch(text, /Reg\. No\./);
    assert.match(text, /Dr\. Priya Sharma/);
  }
});

test("formatPrescriptionPlainText always includes computer-generated disclaimer", () => {
  const text = formatPrescriptionPlainText({
    draft: DRAFT,
    patient: PATIENT,
    doctor: { full_name: "Priya Sharma", clinic_name: "Care Clinic" },
  });

  assert.match(text, new RegExp(PRESCRIPTION_COMPUTER_GENERATED_DISCLAIMER.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  assert.doesNotMatch(text, /_{5,}/);
});

test("buildPrescriptionPrintHtml (PDF path) includes disclaimer and optional registration", () => {
  const withLicense = buildPrescriptionPrintHtml({
    draft: DRAFT,
    patient: PATIENT,
    doctor: {
      full_name: "Priya Sharma",
      clinic_name: "Care Clinic",
      license_number: "TNMC-7788",
    },
  });
  assert.match(withLicense, /Reg\. No\. TNMC-7788/);
  assert.match(withLicense, /computer-generated prescription/);

  const withoutLicense = buildPrescriptionPrintHtml({
    draft: DRAFT,
    patient: PATIENT,
    doctor: { full_name: "Priya Sharma", clinic_name: "Care Clinic" },
  });
  assert.doesNotMatch(withoutLicense, /Reg\. No\./);
  assert.match(withoutLicense, /computer-generated prescription/);
});

test("PRESCRIPTION_COMPUTER_GENERATED_DISCLAIMER matches invoice tone", () => {
  assert.equal(
    PRESCRIPTION_COMPUTER_GENERATED_DISCLAIMER,
    "Generated by Nadi AI · This is a computer-generated prescription.",
  );
});
