/**
 * @fileoverview Pure invoice PDF generation (pdf-lib — no headless browser).
 *
 * Builds a single-page consultation invoice with the fields required by the
 * booking payment flow. GST fields are rendered as "NA" placeholders —
 * clinics have no GST number on file yet; do not hardcode one.
 */

import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { formatSlotLabel } from "./slot-engine.js";

/**
 * Formats a per-clinic sequential sequence into a stable invoice number.
 * @param {number|bigint|string} seq
 * @returns {string}
 */
export function formatInvoiceNumber(seq) {
  const n = Number(seq);
  if (!Number.isFinite(n) || n < 1) {
    throw new Error(`invoice sequence must be a positive integer, got ${seq}`);
  }
  return `INV-${String(Math.trunc(n)).padStart(6, "0")}`;
}

/**
 * Builds the display lines used on the PDF (also unit-tested for field
 * correctness without needing to scrape PDF binary text).
 *
 * @param {{
 *   clinicName: string;
 *   clinicAddress?: string|null;
 *   doctorName: string;
 *   patientName: string;
 *   slotStart: string|Date;
 *   consultationAmount: number|string|null|undefined;
 *   razorpayPaymentId: string;
 *   invoiceNumber: string;
 * }} fields
 * @returns {{
 *   title: string;
 *   invoiceNumber: string;
 *   clinicName: string;
 *   clinicAddress: string;
 *   doctorName: string;
 *   patientName: string;
 *   appointmentDateTime: string;
 *   consultationAmount: string;
 *   razorpayPaymentId: string;
 *   gstin: string;
 *   cgst: string;
 *   sgst: string;
 * }}
 */
export function buildInvoiceDisplayFields(fields) {
  const slotStart =
    fields.slotStart instanceof Date
      ? fields.slotStart
      : new Date(fields.slotStart);

  const amountRaw = fields.consultationAmount;
  const amountNum =
    amountRaw == null || amountRaw === ""
      ? null
      : Number(amountRaw);
  const consultationAmount =
    amountNum != null && Number.isFinite(amountNum)
      ? `INR ${amountNum.toFixed(2)}`
      : "NA";

  return {
    title: "Consultation Invoice",
    invoiceNumber: fields.invoiceNumber,
    clinicName: fields.clinicName?.trim() || "Clinic",
    clinicAddress: fields.clinicAddress?.trim() || "NA",
    doctorName: fields.doctorName?.trim() || "NA",
    patientName: fields.patientName?.trim() || "NA",
    appointmentDateTime: Number.isNaN(slotStart.getTime())
      ? "NA"
      : formatSlotLabel(slotStart),
    consultationAmount,
    razorpayPaymentId: fields.razorpayPaymentId?.trim() || "NA",
    // GST not configured per clinic yet — leave blank/NA, never invent a GSTIN.
    gstin: "NA",
    cgst: "NA",
    sgst: "NA",
  };
}

/**
 * Generates a PDF invoice and returns its bytes.
 *
 * @param {Parameters<typeof buildInvoiceDisplayFields>[0]} fields
 * @returns {Promise<Uint8Array>}
 */
export async function generateInvoicePdf(fields) {
  const display = buildInvoiceDisplayFields(fields);
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595.28, 841.89]); // A4
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);

  const margin = 50;
  let y = 780;
  const lineGap = 22;
  const labelColor = rgb(0.35, 0.35, 0.35);
  const valueColor = rgb(0.1, 0.1, 0.1);

  const drawTitle = (text) => {
    page.drawText(text, {
      x: margin,
      y,
      size: 18,
      font: fontBold,
      color: valueColor,
    });
    y -= 36;
  };

  /** @param {string} label @param {string} value */
  const drawRow = (label, value) => {
    page.drawText(label, {
      x: margin,
      y,
      size: 10,
      font,
      color: labelColor,
    });
    page.drawText(String(value), {
      x: margin + 160,
      y,
      size: 11,
      font: fontBold,
      color: valueColor,
      maxWidth: 330,
    });
    y -= lineGap;
  };

  drawTitle(display.title);
  drawRow("Invoice number", display.invoiceNumber);
  drawRow("Clinic", display.clinicName);
  drawRow("Clinic address", display.clinicAddress);
  drawRow("Doctor", display.doctorName);
  drawRow("Patient", display.patientName);
  drawRow("Appointment", display.appointmentDateTime);
  drawRow("Consultation amount", display.consultationAmount);
  drawRow("Razorpay payment ID", display.razorpayPaymentId);

  y -= 12;
  page.drawText("Tax details", {
    x: margin,
    y,
    size: 12,
    font: fontBold,
    color: valueColor,
  });
  y -= lineGap;
  drawRow("GSTIN", display.gstin);
  drawRow("CGST", display.cgst);
  drawRow("SGST", display.sgst);

  y -= 24;
  page.drawText("Generated by Nadi AI · This is a computer-generated invoice.", {
    x: margin,
    y,
    size: 9,
    font,
    color: labelColor,
  });

  return pdf.save();
}
