import { SOAP_GENERATION_CONFIG } from "../constants.js";

export const SOAP_JSON_SCHEMA = {
  name: "nadi_ai_soap_note",
  schema: {
    type: "object",
    additionalProperties: false,
    required: [
      "subjective",
      "objective",
      "assessment",
      "plan",
      "chiefComplaint",
      "historyOfPresentIllness",
      "clinicalSummary",
    ],
    properties: {
      subjective: { type: "string" },
      objective: { type: "string" },
      assessment: { type: "string" },
      plan: { type: "string" },
      chiefComplaint: { type: "string" },
      historyOfPresentIllness: { type: "string" },
      clinicalSummary: { type: "string" },
    },
  },
  strict: true,
};

export function buildSOAPPrompt(context) {
  return [
    {
      role: "system",
      content: [
        "You are Nadi AI, a clinical documentation assistant for Indian outpatient general practice clinics.",
        "Generate only a structured SOAP note as JSON matching the provided schema.",
        "Use ONLY information explicitly present in the reviewed transcript and provided context.",
        "Do not fabricate diagnoses, medications, vitals, test results, allergies, examination findings, or follow-up plans.",
        "If information is not available, write 'Not documented in transcript.'",
        "Do not include prescriptions unless a medication was explicitly discussed in the transcript.",
        "Keep language professional, concise, and suitable for a doctor to review.",
      ].join("\n"),
    },
    {
      role: "user",
      content: [
        `Prompt version: ${SOAP_GENERATION_CONFIG.PROMPT_VERSION}`,
        "",
        "PATIENT CONTEXT:",
        safeJson(context.patient ?? {}),
        "",
        "DOCTOR CONTEXT:",
        safeJson(context.doctor ?? {}),
        "",
        "CONSULTATION CONTEXT:",
        safeJson(context.consultation ?? {}),
        "",
        "REVIEWED TRANSCRIPT:",
        context.transcriptText || "Not documented in transcript.",
        "",
        "TASK: Create a SOAP note for this consultation.",
        "",
        "DETAILED INSTRUCTIONS FOR EACH SECTION:",
        "",
        "1. SUBJECTIVE (Patient's narrative):",
        "   - Chief complaint: What brought the patient in? (one concise statement)",
        "   - History of present illness (HPI): Timeline and progression of symptoms",
        "     * Include onset, duration, severity, character, location, associated symptoms",
        "     * What makes it better or worse?",
        "     * Any previous similar episodes?",
        "   - Relevant PMH: Only mention if discussed in context of current complaint",
        "   - Current medications: Only if explicitly mentioned",
        "   - If not documented, state 'Not documented in transcript.'",
        "",
        "2. OBJECTIVE (Factual findings):",
        "   - Vital signs: Temperature, BP, HR, RR, O2 sat, weight (if mentioned)",
        "   - Physical examination: Only actual observations (not impressions)",
        "     * Include specific findings (e.g., 'Abdomen: soft, non-tender' not 'abdomen normal')",
        "   - Lab/test results: Only values explicitly discussed (not interpretations)",
        "   - General appearance: Only if specifically noted by doctor",
        "   - If no objective findings documented, state 'Not documented in transcript.'",
        "",
        "3. ASSESSMENT (Clinical interpretation):",
        "   - Primary impression: What is the doctor's clinical impression?",
        "   - Differential diagnoses: If mentioned, list with reasoning if provided",
        "   - Severity assessment: Mild, moderate, severe (only if discussed)",
        "   - Do NOT invent diagnoses. If no clear assessment given, state 'Clinical impression not documented.'",
        "",
        "4. PLAN (Management strategy):",
        "   - Investigations ordered: Specific tests (not 'need more tests')",
        "   - Medications: Include drug name, dose, route, frequency, duration if discussed",
        "   - Lifestyle modifications: Diet, exercise, activity restrictions",
        "   - Referrals: Any specialist referrals mentioned?",
        "   - Follow-up: When and what to monitor?",
        "   - Safety precautions: Any warnings or red flag symptoms to watch for?",
        "   - If no plan documented, state 'Not documented in transcript.'",
        "",
        "5. CLINICAL SUMMARY:",
        "   - 2-3 sentence summary suitable for quick reference or handoff",
        "   - Include: chief complaint, relevant findings, and key management point",
        "",
        "QUALITY CHECKS BEFORE RETURNING:",
        "   ✓ Chief complaint is specific and reflects patient's actual words when possible",
        "   ✓ HPI follows chronological progression from onset to present",
        "   ✓ Objective findings are actual observations, not interpretations",
        "   ✓ Assessment reflects only clinical reasoning supported by documented findings",
        "   ✓ Plan contains actionable, specific instructions (not vague statements)",
        "   ✓ All dosages and frequencies are exactly as discussed",
        "   ✓ No speculation or assumptions about undocumented areas",
      ].join("\n"),
    },
  ];
}

function safeJson(value) {
  return JSON.stringify(value, null, 2);
}
