/**
 * @fileoverview Client-safe public API for the scribe feature.
 *
 * Safe to import from Client Components. Must never re-export Node-only
 * modules (prescription-pdf, createScribeServices, repositories, etc.).
 *
 * Usage:
 *   import { ACTIVE_CONSULTATION_STATUSES } from "@/features/scribe/client";
 *   // or via the barrel: import { ... } from "@/features/scribe";
 */

export {
  SESSION_STATUS,
  VALID_TRANSITIONS,
  TERMINAL_STATUSES,
  RECORDING_BLOCKING_STATUSES,
  ACTIVE_CONSULTATION_STATUSES,
  HISTORY_CONSULTATION_STATUSES,
  SOAP_VIEWABLE_SESSION_STATUSES,
  PROCESSING_STATUSES,
  ACTIONABLE_STATUSES,
  SCRIBE_LANGUAGE,
  JOB_TYPE,
  JOB_STATUS,
  JOB_PRIORITY,
  TRANSCRIPTION_STATUS,
  TRANSCRIPTION_CONFIG,
  AI_PROVIDER,
  SOAP_NOTE_STATUS,
  SOAP_SECTION,
  SOAP_GENERATION_CONFIG,
  PRESCRIPTION_DRAFT_STATUS,
  PRESCRIPTION_REVIEW_STATUS,
  PRESCRIPTION_GENERATION_CONFIG,
  AUDIT_ACTION,
  SCRIBE_LIMITS,
  SCRIBE_STORAGE,
  PRESCRIPTION_STORAGE,
} from "./constants.js";

export {
  ScribeError,
  SessionNotFoundError,
  InvalidStateTransitionError,
  SessionFinalizedError,
  SessionAlreadyActiveError,
  UnauthorizedSessionAccessError,
  SessionValidationError,
  SessionConflictError,
  DatabaseError,
  AuditLogError,
  StorageError,
  UploadValidationError,
  UploadNotReadyError,
  UploadExpiredError,
  UploadIntegrityError,
  TranscriptionNotReadyError,
  TranscriptionProviderError,
  TranscriptionRetryExhaustedError,
  WorkerUnauthorizedError,
  SOAPGenerationError,
  SOAPValidationError,
  SOAPNotReadyError,
  QuotaExceededError,
  PrescriptionNotReadyError,
  PrescriptionGenerationError,
  PrescriptionReviewError,
  MissingDoctorRegistrationError,
  PrescriptionValidationError,
  isScribeError,
  toApiError,
} from "./errors.js";

export {
  CreateSessionSchema,
  UpdateSessionSchema,
  TransitionStateSchema,
  FinalizeSessionSchema,
  RegisterChunkSchema,
  StartAudioUploadSchema,
  UploadChunkManifestSchema,
  ConfirmAudioChunkSchema,
  RetryAudioUploadSchema,
  FinalizeAudioUploadSchema,
  QueueTranscriptionSchema,
  RetryTranscriptionSchema,
  TranscriptionWorkerSchema,
  RecoverTranscriptionJobsSchema,
  ReviewSegmentUpdateSchema,
  SaveTranscriptVersionSchema,
  RestoreTranscriptVersionSchema,
  CompleteReviewSchema,
  SOAPNoteSchema,
  GenerateSOAPNoteSchema,
  RetrySOAPGenerationSchema,
  SOAPSectionKeySchema,
  UpdateSOAPSectionSchema,
  SaveSOAPVersionSchema,
  CompareSOAPVersionsSchema,
  ApproveSOAPNoteSchema,
  RejectSOAPNoteSchema,
  SessionFilterSchema,
  PatchSessionSchema,
  TranscriptSegmentSchema,
  PrescriptionDraftSchema,
  PrescriptionMedicationSchema,
  GeneratePrescriptionSchema,
  RetryPrescriptionGenerationSchema,
  UpdatePrescriptionDraftSchema,
  SavePrescriptionVersionSchema,
  ApprovePrescriptionSchema,
  RejectPrescriptionSchema,
} from "./schemas.js";

export { createLogger, scribeLogger } from "./logger.js";
